// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLSV;

#nullable disable

namespace QLSV.Migrations
{
    [DbContext(typeof(EFDbContext))]
    partial class EFDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLDSV.Models.BangDiem", b =>
                {
                    b.Property<long>("LopTCID")
                        .HasColumnType("bigint");

                    b.Property<long>("MaSoSV")
                        .HasColumnType("bigint");

                    b.Property<decimal>("DiemChuyenCan")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("DiemGiuaKy")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("DiemTB")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("DiemThiCuoiKy")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<short>("TiLeDiemQuaTrinh")
                        .HasColumnType("smallint");

                    b.Property<short>("TiLeDiemThiCuoiKy")
                        .HasColumnType("smallint");

                    b.HasKey("LopTCID", "MaSoSV");

                    b.HasIndex("MaSoSV");

                    b.ToTable("BangDiems");

                    b.HasData(
                        new
                        {
                            LopTCID = 1L,
                            MaSoSV = 1L,
                            DiemChuyenCan = 10m,
                            DiemGiuaKy = 9m,
                            DiemTB = 9.15m,
                            DiemThiCuoiKy = 9m,
                            TiLeDiemQuaTrinh = (short)50,
                            TiLeDiemThiCuoiKy = (short)50
                        },
                        new
                        {
                            LopTCID = 2L,
                            MaSoSV = 1L,
                            DiemChuyenCan = 8m,
                            DiemGiuaKy = 9m,
                            DiemTB = 7.85m,
                            DiemThiCuoiKy = 7m,
                            TiLeDiemQuaTrinh = (short)50,
                            TiLeDiemThiCuoiKy = (short)50
                        },
                        new
                        {
                            LopTCID = 3L,
                            MaSoSV = 1L,
                            DiemChuyenCan = 8m,
                            DiemGiuaKy = 8m,
                            DiemTB = 8m,
                            DiemThiCuoiKy = 8m,
                            TiLeDiemQuaTrinh = (short)50,
                            TiLeDiemThiCuoiKy = (short)50
                        },
                        new
                        {
                            LopTCID = 4L,
                            MaSoSV = 1L,
                            DiemChuyenCan = 10m,
                            DiemGiuaKy = 7m,
                            DiemTB = 7.95m,
                            DiemThiCuoiKy = 8m,
                            TiLeDiemQuaTrinh = (short)50,
                            TiLeDiemThiCuoiKy = (short)50
                        },
                        new
                        {
                            LopTCID = 5L,
                            MaSoSV = 1L,
                            DiemChuyenCan = 8m,
                            DiemGiuaKy = 10m,
                            DiemTB = 7.7m,
                            DiemThiCuoiKy = 6m,
                            TiLeDiemQuaTrinh = (short)50,
                            TiLeDiemThiCuoiKy = (short)50
                        },
                        new
                        {
                            LopTCID = 1L,
                            MaSoSV = 2L,
                            DiemChuyenCan = 7m,
                            DiemGiuaKy = 5m,
                            DiemTB = 7.3m,
                            DiemThiCuoiKy = 9m,
                            TiLeDiemQuaTrinh = (short)50,
                            TiLeDiemThiCuoiKy = (short)50
                        },
                        new
                        {
                            LopTCID = 2L,
                            MaSoSV = 2L,
                            DiemChuyenCan = 9m,
                            DiemGiuaKy = 9m,
                            DiemTB = 9m,
                            DiemThiCuoiKy = 9m,
                            TiLeDiemQuaTrinh = (short)50,
                            TiLeDiemThiCuoiKy = (short)50
                        },
                        new
                        {
                            LopTCID = 3L,
                            MaSoSV = 2L,
                            DiemChuyenCan = 10m,
                            DiemGiuaKy = 7m,
                            DiemTB = 7.45m,
                            DiemThiCuoiKy = 7m,
                            TiLeDiemQuaTrinh = (short)50,
                            TiLeDiemThiCuoiKy = (short)50
                        },
                        new
                        {
                            LopTCID = 4L,
                            MaSoSV = 2L,
                            DiemChuyenCan = 10m,
                            DiemGiuaKy = 9m,
                            DiemTB = 9.15m,
                            DiemThiCuoiKy = 9m,
                            TiLeDiemQuaTrinh = (short)50,
                            TiLeDiemThiCuoiKy = (short)50
                        },
                        new
                        {
                            LopTCID = 6L,
                            MaSoSV = 2L,
                            DiemChuyenCan = 4m,
                            DiemGiuaKy = 5m,
                            DiemTB = 6.35m,
                            DiemThiCuoiKy = 8m,
                            TiLeDiemQuaTrinh = (short)50,
                            TiLeDiemThiCuoiKy = (short)50
                        },
                        new
                        {
                            LopTCID = 1L,
                            MaSoSV = 3L,
                            DiemChuyenCan = 9m,
                            DiemGiuaKy = 10m,
                            DiemTB = 7.85m,
                            DiemThiCuoiKy = 6m,
                            TiLeDiemQuaTrinh = (short)50,
                            TiLeDiemThiCuoiKy = (short)50
                        },
                        new
                        {
                            LopTCID = 2L,
                            MaSoSV = 3L,
                            DiemChuyenCan = 10m,
                            DiemGiuaKy = 8.8m,
                            DiemTB = 9.18m,
                            DiemThiCuoiKy = 9.2m,
                            TiLeDiemQuaTrinh = (short)50,
                            TiLeDiemThiCuoiKy = (short)50
                        },
                        new
                        {
                            LopTCID = 3L,
                            MaSoSV = 3L,
                            DiemChuyenCan = 8m,
                            DiemGiuaKy = 6.5m,
                            DiemTB = 6.23m,
                            DiemThiCuoiKy = 5.5m,
                            TiLeDiemQuaTrinh = (short)50,
                            TiLeDiemThiCuoiKy = (short)50
                        },
                        new
                        {
                            LopTCID = 4L,
                            MaSoSV = 3L,
                            DiemChuyenCan = 9m,
                            DiemGiuaKy = 7.8m,
                            DiemTB = 7.98m,
                            DiemThiCuoiKy = 7.8m,
                            TiLeDiemQuaTrinh = (short)50,
                            TiLeDiemThiCuoiKy = (short)50
                        },
                        new
                        {
                            LopTCID = 5L,
                            MaSoSV = 3L,
                            DiemChuyenCan = 7m,
                            DiemGiuaKy = 4.5m,
                            DiemTB = 5.43m,
                            DiemThiCuoiKy = 5.6m,
                            TiLeDiemQuaTrinh = (short)50,
                            TiLeDiemThiCuoiKy = (short)50
                        },
                        new
                        {
                            LopTCID = 5L,
                            MaSoSV = 8L,
                            DiemChuyenCan = 10m,
                            DiemGiuaKy = 6.8m,
                            DiemTB = 7.18m,
                            DiemThiCuoiKy = 6.6m,
                            TiLeDiemQuaTrinh = (short)50,
                            TiLeDiemThiCuoiKy = (short)50
                        },
                        new
                        {
                            LopTCID = 6L,
                            MaSoSV = 7L,
                            DiemChuyenCan = 5m,
                            DiemGiuaKy = 5.5m,
                            DiemTB = 6.18m,
                            DiemThiCuoiKy = 7m,
                            TiLeDiemQuaTrinh = (short)50,
                            TiLeDiemThiCuoiKy = (short)50
                        });
                });

            modelBuilder.Entity("QLDSV.Models.GiangVien", b =>
                {
                    b.Property<long>("MaSoGV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MaSoGV"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("HocVi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("KhoaID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenGV")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaSoGV");

                    b.HasIndex("KhoaID");

                    b.ToTable("GiangViens");

                    b.HasData(
                        new
                        {
                            MaSoGV = 1L,
                            Email = "nguyenvana@gmail.com",
                            GioiTinh = true,
                            HocVi = "Thạc sĩ",
                            KhoaID = 1L,
                            NgaySinh = new DateTime(1990, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenGV = "Nguyễn Văn A"
                        },
                        new
                        {
                            MaSoGV = 2L,
                            Email = "tranthib@gmail.com",
                            GioiTinh = false,
                            HocVi = "Tiến sĩ",
                            KhoaID = 2L,
                            NgaySinh = new DateTime(1985, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenGV = "Trần Thị B"
                        },
                        new
                        {
                            MaSoGV = 3L,
                            Email = "levanc@gmail.com",
                            GioiTinh = true,
                            HocVi = "Phó giáo sư",
                            KhoaID = 3L,
                            NgaySinh = new DateTime(1978, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenGV = "Lê Văn C"
                        },
                        new
                        {
                            MaSoGV = 4L,
                            Email = "nguyenthid@gmail.com",
                            GioiTinh = false,
                            HocVi = "Thạc sĩ",
                            KhoaID = 4L,
                            NgaySinh = new DateTime(1992, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenGV = "Nguyễn Thị D"
                        },
                        new
                        {
                            MaSoGV = 5L,
                            Email = "phamvane@gmail.com",
                            GioiTinh = true,
                            HocVi = "Tiến sĩ",
                            KhoaID = 5L,
                            NgaySinh = new DateTime(1980, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenGV = "Phạm Văn E"
                        },
                        new
                        {
                            MaSoGV = 6L,
                            Email = "vuthif@gmail.com",
                            GioiTinh = false,
                            HocVi = "Giáo sư",
                            KhoaID = 6L,
                            NgaySinh = new DateTime(1988, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenGV = "Vũ Thị F"
                        });
                });

            modelBuilder.Entity("QLDSV.Models.Khoa", b =>
                {
                    b.Property<long>("KhoaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("KhoaID"));

                    b.Property<string>("MaKhoa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("KhoaID");

                    b.ToTable("Khoas");

                    b.HasData(
                        new
                        {
                            KhoaID = 1L,
                            MaKhoa = "CNTT",
                            TenKhoa = "Khoa Công nghệ thông tin"
                        },
                        new
                        {
                            KhoaID = 2L,
                            MaKhoa = "KT",
                            TenKhoa = "Khoa Kinh tế"
                        },
                        new
                        {
                            KhoaID = 3L,
                            MaKhoa = "NNA",
                            TenKhoa = "Khoa Ngôn ngữ Anh"
                        },
                        new
                        {
                            KhoaID = 4L,
                            MaKhoa = "XD",
                            TenKhoa = "Khoa Xây dựng"
                        },
                        new
                        {
                            KhoaID = 5L,
                            MaKhoa = "CB",
                            TenKhoa = "Khoa Cơ bản"
                        },
                        new
                        {
                            KhoaID = 6L,
                            MaKhoa = "QTKD",
                            TenKhoa = "Khoa Quản trị kinh doanh"
                        });
                });

            modelBuilder.Entity("QLDSV.Models.LopDanhNghia", b =>
                {
                    b.Property<long>("LopDNID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LopDNID"));

                    b.Property<long>("KhoaID")
                        .HasColumnType("bigint");

                    b.Property<string>("MaLopDN")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<long>("MaSoGV")
                        .HasColumnType("bigint");

                    b.Property<short>("NamNhapHocCuaSV")
                        .HasColumnType("smallint");

                    b.Property<int>("SoLuongSV")
                        .HasColumnType("int");

                    b.HasKey("LopDNID");

                    b.HasIndex("KhoaID");

                    b.HasIndex("MaSoGV");

                    b.ToTable("LopDanhNghias");

                    b.HasData(
                        new
                        {
                            LopDNID = 1L,
                            KhoaID = 1L,
                            MaLopDN = "22ĐHTT06",
                            MaSoGV = 1L,
                            NamNhapHocCuaSV = (short)2022,
                            SoLuongSV = 60
                        },
                        new
                        {
                            LopDNID = 2L,
                            KhoaID = 2L,
                            MaLopDN = "21ĐHKT01",
                            MaSoGV = 2L,
                            NamNhapHocCuaSV = (short)2021,
                            SoLuongSV = 50
                        },
                        new
                        {
                            LopDNID = 3L,
                            KhoaID = 3L,
                            MaLopDN = "20ĐHNA03",
                            MaSoGV = 3L,
                            NamNhapHocCuaSV = (short)2020,
                            SoLuongSV = 40
                        },
                        new
                        {
                            LopDNID = 4L,
                            KhoaID = 4L,
                            MaLopDN = "22ĐHXD02",
                            MaSoGV = 4L,
                            NamNhapHocCuaSV = (short)2022,
                            SoLuongSV = 55
                        },
                        new
                        {
                            LopDNID = 5L,
                            KhoaID = 5L,
                            MaLopDN = "19ĐHQT04",
                            MaSoGV = 5L,
                            NamNhapHocCuaSV = (short)2019,
                            SoLuongSV = 45
                        },
                        new
                        {
                            LopDNID = 6L,
                            KhoaID = 6L,
                            MaLopDN = "21ĐHQT02",
                            MaSoGV = 6L,
                            NamNhapHocCuaSV = (short)2021,
                            SoLuongSV = 60
                        });
                });

            modelBuilder.Entity("QLDSV.Models.LopTinChi", b =>
                {
                    b.Property<long>("LopTCID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LopTCID"));

                    b.Property<string>("HocKy")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<long>("KhoaID")
                        .HasColumnType("bigint");

                    b.Property<string>("MaLopTC")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<long>("MaMon")
                        .HasColumnType("bigint");

                    b.Property<long>("MaSoGV")
                        .HasColumnType("bigint");

                    b.Property<short>("NamHoc")
                        .HasColumnType("smallint");

                    b.HasKey("LopTCID");

                    b.HasIndex("KhoaID");

                    b.HasIndex("MaMon");

                    b.HasIndex("MaSoGV");

                    b.ToTable("LopTinChis");

                    b.HasData(
                        new
                        {
                            LopTCID = 1L,
                            HocKy = "2",
                            KhoaID = 2L,
                            MaLopTC = "22ĐHKT01",
                            MaMon = 2L,
                            MaSoGV = 2L,
                            NamHoc = (short)2024
                        },
                        new
                        {
                            LopTCID = 2L,
                            HocKy = "1",
                            KhoaID = 1L,
                            MaLopTC = "23ĐHTT01",
                            MaMon = 1L,
                            MaSoGV = 1L,
                            NamHoc = (short)2023
                        },
                        new
                        {
                            LopTCID = 3L,
                            HocKy = "2",
                            KhoaID = 3L,
                            MaLopTC = "22ĐHNA01",
                            MaMon = 3L,
                            MaSoGV = 3L,
                            NamHoc = (short)2024
                        },
                        new
                        {
                            LopTCID = 4L,
                            HocKy = "1",
                            KhoaID = 4L,
                            MaLopTC = "23ĐHXD01",
                            MaMon = 4L,
                            MaSoGV = 4L,
                            NamHoc = (short)2023
                        },
                        new
                        {
                            LopTCID = 5L,
                            HocKy = "2",
                            KhoaID = 5L,
                            MaLopTC = "22ĐHQT01",
                            MaMon = 5L,
                            MaSoGV = 5L,
                            NamHoc = (short)2024
                        },
                        new
                        {
                            LopTCID = 6L,
                            HocKy = "1",
                            KhoaID = 6L,
                            MaLopTC = "23ĐHTT06",
                            MaMon = 6L,
                            MaSoGV = 6L,
                            NamHoc = (short)2023
                        });
                });

            modelBuilder.Entity("QLDSV.Models.MonHoc", b =>
                {
                    b.Property<long>("MaMon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MaMon"));

                    b.Property<long>("KhoaID")
                        .HasColumnType("bigint");

                    b.Property<int>("SoTietLT")
                        .HasColumnType("int");

                    b.Property<int>("SoTietTH")
                        .HasColumnType("int");

                    b.Property<int>("SoTinChi")
                        .HasColumnType("int");

                    b.Property<string>("TenMon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaMon");

                    b.HasIndex("KhoaID");

                    b.ToTable("MonHocs");

                    b.HasData(
                        new
                        {
                            MaMon = 1L,
                            KhoaID = 1L,
                            SoTietLT = 45,
                            SoTietTH = 0,
                            SoTinChi = 3,
                            TenMon = "Lập trình Windows"
                        },
                        new
                        {
                            MaMon = 2L,
                            KhoaID = 2L,
                            SoTietLT = 60,
                            SoTietTH = 0,
                            SoTinChi = 4,
                            TenMon = "Kế toán tài chính"
                        },
                        new
                        {
                            MaMon = 3L,
                            KhoaID = 3L,
                            SoTietLT = 45,
                            SoTietTH = 0,
                            SoTinChi = 3,
                            TenMon = "Văn học Anh"
                        },
                        new
                        {
                            MaMon = 4L,
                            KhoaID = 4L,
                            SoTietLT = 60,
                            SoTietTH = 30,
                            SoTinChi = 4,
                            TenMon = "Kỹ thuật xây dựng"
                        },
                        new
                        {
                            MaMon = 5L,
                            KhoaID = 5L,
                            SoTietLT = 45,
                            SoTietTH = 0,
                            SoTinChi = 3,
                            TenMon = "Toán cao cấp"
                        },
                        new
                        {
                            MaMon = 6L,
                            KhoaID = 6L,
                            SoTietLT = 45,
                            SoTietTH = 0,
                            SoTinChi = 3,
                            TenMon = "Quản trị nhân sự"
                        });
                });

            modelBuilder.Entity("QLDSV.Models.SinhVien", b =>
                {
                    b.Property<long>("MaSoSV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MaSoSV"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<long>("LopDNID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TenSV")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaSoSV");

                    b.HasIndex("LopDNID");

                    b.ToTable("SinhViens");

                    b.HasData(
                        new
                        {
                            MaSoSV = 1L,
                            DiaChi = "Số 10, Đường Trần Hưng Đạo, Quận 1, Thành phố Hồ Chí Minh",
                            Email = "annv@gmail.com",
                            GioiTinh = true,
                            LopDNID = 1L,
                            NgaySinh = new DateTime(2004, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0827983728",
                            TenSV = "Nguyễn Văn An",
                            TrangThai = true
                        },
                        new
                        {
                            MaSoSV = 2L,
                            DiaChi = "Số 5, Đường Lê Lợi, Quận Hải Châu, Thành phố Đà Nẵng",
                            Email = "bichtt@gmail.com",
                            GioiTinh = false,
                            LopDNID = 2L,
                            NgaySinh = new DateTime(2003, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0912345678",
                            TenSV = "Trần Thị Bích",
                            TrangThai = true
                        },
                        new
                        {
                            MaSoSV = 3L,
                            DiaChi = "Số 15, Đường Phan Đình Phùng, Quận Ba Đình, Hà Nội",
                            Email = "chaulm@gmail.com",
                            GioiTinh = false,
                            LopDNID = 1L,
                            NgaySinh = new DateTime(2002, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0938765432",
                            TenSV = "Lê Minh Châu",
                            TrangThai = true
                        },
                        new
                        {
                            MaSoSV = 4L,
                            DiaChi = "Số 20, Đường Nguyễn Trãi, Quận Thanh Xuân, Hà Nội",
                            Email = "datpq@gmail.com",
                            GioiTinh = true,
                            LopDNID = 3L,
                            NgaySinh = new DateTime(2001, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0987654321",
                            TenSV = "Phạm Quốc Đạt",
                            TrangThai = true
                        },
                        new
                        {
                            MaSoSV = 5L,
                            DiaChi = "Số 25, Đường Lý Tự Trọng, Quận Ninh Kiều, Thành phố Cần Thơ",
                            Email = "hoath@gmail.com",
                            GioiTinh = false,
                            LopDNID = 2L,
                            NgaySinh = new DateTime(2004, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0856738291",
                            TenSV = "Hoàng Thị Hoa",
                            TrangThai = true
                        },
                        new
                        {
                            MaSoSV = 6L,
                            DiaChi = "Số 8, Đường Trường Sa, Quận Ngũ Hành Sơn, Thành phố Đà Nẵng",
                            Email = "hungvd@gmail.com",
                            GioiTinh = true,
                            LopDNID = 1L,
                            NgaySinh = new DateTime(2003, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0827364529",
                            TenSV = "Vũ Đức Hùng",
                            TrangThai = true
                        },
                        new
                        {
                            MaSoSV = 7L,
                            DiaChi = "Số 12, Đường Nguyễn Huệ, Quận 1, Thành phố Hồ Chí Minh",
                            Email = "landt@gmail.com",
                            GioiTinh = false,
                            LopDNID = 2L,
                            NgaySinh = new DateTime(2002, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0918374652",
                            TenSV = "Đặng Thị Lan",
                            TrangThai = true
                        },
                        new
                        {
                            MaSoSV = 8L,
                            DiaChi = "Số 30, Đường Lê Duẩn, Quận 1, Thành phố Hồ Chí Minh",
                            Email = "liembt@gmail.com",
                            GioiTinh = true,
                            LopDNID = 3L,
                            NgaySinh = new DateTime(2001, 7, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0908765432",
                            TenSV = "Bùi Thanh Liêm",
                            TrangThai = true
                        },
                        new
                        {
                            MaSoSV = 9L,
                            DiaChi = "Số 50, Đường Điện Biên Phủ, Quận Bình Thạnh, Thành phố Hồ Chí Minh",
                            Email = "maidt@gmail.com",
                            GioiTinh = false,
                            LopDNID = 1L,
                            NgaySinh = new DateTime(2003, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0927364518",
                            TenSV = "Đỗ Thị Mai",
                            TrangThai = true
                        },
                        new
                        {
                            MaSoSV = 10L,
                            DiaChi = "Số 18, Đường Nguyễn Thị Minh Khai, Quận 1, Thành phố Hồ Chí Minh",
                            Email = "namnt@gmail.com",
                            GioiTinh = true,
                            LopDNID = 2L,
                            NgaySinh = new DateTime(2002, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0938472651",
                            TenSV = "Ngô Thanh Nam",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("QLDSV.Models.TaiKhoan", b =>
                {
                    b.Property<int>("TaiKhoanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaiKhoanID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("RoleID")
                        .HasMaxLength(6)
                        .HasColumnType("tinyint");

                    b.Property<bool>("TinhTrang")
                        .HasColumnType("bit");

                    b.HasKey("TaiKhoanID");

                    b.ToTable("TaiKhoans");

                    b.HasData(
                        new
                        {
                            TaiKhoanID = -1,
                            Email = "admin@gmail.com",
                            MatKhau = "111",
                            RoleID = (byte)1,
                            TinhTrang = true
                        },
                        new
                        {
                            TaiKhoanID = 1,
                            Email = "nguyenvana@gmail.com",
                            MatKhau = "111",
                            RoleID = (byte)2,
                            TinhTrang = true
                        },
                        new
                        {
                            TaiKhoanID = 2,
                            Email = "tranthib@gmail.com",
                            MatKhau = "111",
                            RoleID = (byte)2,
                            TinhTrang = true
                        },
                        new
                        {
                            TaiKhoanID = 3,
                            Email = "levanc@gmail.com",
                            MatKhau = "111",
                            RoleID = (byte)2,
                            TinhTrang = true
                        },
                        new
                        {
                            TaiKhoanID = 4,
                            Email = "nguyenthid@gmail.com",
                            MatKhau = "111",
                            RoleID = (byte)2,
                            TinhTrang = true
                        });
                });

            modelBuilder.Entity("QLDSV.Models.BangDiem", b =>
                {
                    b.HasOne("QLDSV.Models.LopTinChi", "LopTinChi")
                        .WithMany("BangDiems")
                        .HasForeignKey("LopTCID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLDSV.Models.SinhVien", "SinhVien")
                        .WithMany()
                        .HasForeignKey("MaSoSV")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LopTinChi");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("QLDSV.Models.GiangVien", b =>
                {
                    b.HasOne("QLDSV.Models.Khoa", "Khoa")
                        .WithMany("GiangViens")
                        .HasForeignKey("KhoaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("QLDSV.Models.LopDanhNghia", b =>
                {
                    b.HasOne("QLDSV.Models.Khoa", "Khoa")
                        .WithMany("LopDanhNghias")
                        .HasForeignKey("KhoaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLDSV.Models.GiangVien", "GiangVien")
                        .WithMany()
                        .HasForeignKey("MaSoGV")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GiangVien");

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("QLDSV.Models.LopTinChi", b =>
                {
                    b.HasOne("QLDSV.Models.Khoa", "Khoa")
                        .WithMany("LopTinChis")
                        .HasForeignKey("KhoaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLDSV.Models.MonHoc", "MonHoc")
                        .WithMany("LopTinChis")
                        .HasForeignKey("MaMon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLDSV.Models.GiangVien", "GiangVien")
                        .WithMany()
                        .HasForeignKey("MaSoGV")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GiangVien");

                    b.Navigation("Khoa");

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("QLDSV.Models.MonHoc", b =>
                {
                    b.HasOne("QLDSV.Models.Khoa", "Khoa")
                        .WithMany("MonHocs")
                        .HasForeignKey("KhoaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("QLDSV.Models.SinhVien", b =>
                {
                    b.HasOne("QLDSV.Models.LopDanhNghia", "LopDanhNghia")
                        .WithMany("SinhViens")
                        .HasForeignKey("LopDNID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LopDanhNghia");
                });

            modelBuilder.Entity("QLDSV.Models.Khoa", b =>
                {
                    b.Navigation("GiangViens");

                    b.Navigation("LopDanhNghias");

                    b.Navigation("LopTinChis");

                    b.Navigation("MonHocs");
                });

            modelBuilder.Entity("QLDSV.Models.LopDanhNghia", b =>
                {
                    b.Navigation("SinhViens");
                });

            modelBuilder.Entity("QLDSV.Models.LopTinChi", b =>
                {
                    b.Navigation("BangDiems");
                });

            modelBuilder.Entity("QLDSV.Models.MonHoc", b =>
                {
                    b.Navigation("LopTinChis");
                });
#pragma warning restore 612, 618
        }
    }
}
